services:
  db:
    container_name: postgres
    image: postgres:17.0
    hostname: ${DB_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tanstack']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tanstack
volumes:
  pgdata:
    name: tanstack-pgdata
networks:
  tanstack:
    name: tanstack-network
